services:
  - name: purrpals-backend
    type: web
    runtime: node
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: purrpalsdata
          property: connectionString
      - key: JWT_SECRET
        value: "your-secret-key"
      - key: NODE_ENV
        value: production

  - name: purrpals-frontend
    type: web
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://purrpals-backend.onrender.com"

databases:
  - name: purrpalsdata
    plan: free
    databaseName: purrpalsdata
    user: purrpalsdata_user 
  
